server:
  port: 8083
feign:
  client:
    config:
      product-service:
        connect-timeout: 3000       # 3 seconds to connect
        read-timeout: 5000          # 5 seconds to read response
        logger-level: BASIC
  circuit-breaker:
    enabled: true
services:
  product:
    url: http://localhost:8082

spring:
  main:
    allow-circular-references: true
  flyway: vi;;h
  enabled: false
  baseline-on-migrate: true
  baseline-version: 1
  application:
    name: product
  cloud:
    discovery:
      enabled=false:
  datasource:
    url: jdbc:mysql://localhost:3306/pbp_ecomm
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: K+vwZZME6tA3QtVtrC3FooGViC4ohLkD45KNEDensRw=          # min 256-bit key in production
  access-token-expiry-ms: 900000  # 15 minutes
  refresh-token-expiry-ms: 604800000  # 7 days

security:
  bcrypt-strength: 12
  max-login-attempts: 5
  lockout-duration-minutes: 30

logging:
  level:
    root: Debug
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            bind: TRACE
    com.ecommerce.auth: INFO
    org.springframework.security: WARN